### ISSUE TITLE
Bash scripts need to be updated to work with Docker Compose V1 and V2

### ISSUE THREAD

**Issue by palyca** [interuss/monitoring#113]
Problem Description:
Bash Scripts that reference docker container names need to be updated to work with the differences that Docker Compose V1 and V2 create as documented here: 

https://docs.docker.com/compose/migrate/

Namely that dashes are used instead of underscores in the naming convention.
For example:

- V1:  dss_sandbox_local-dss-core-service_1
- V2: dss_sandbox-local-dss-core-service-1

Recreation Steps:
1. create a docker image using a Docker Version 2 
2. cd to interuss/monitoring
3. run make start_locally.sh
4. The newly built container using Docker Compose Version 2 will not status as started as shown below:
palyca-macbookpro1:monitoring palyca$ make start-locally
build/dev/run_locally.sh up -d
[+] Building 0.0s (0/0)                                                                                                                                                                         
[+] Running 5/5
 ✔ Container dss_sandbox-local-dss-crdb-1              Started                                                                                                                             0.2s 
 ✔ Container dss_sandbox-local-dss-dummy-oauth-1       Started                                                                                                                             0.2s 
 ✔ Container dss_sandbox-local-dss-rid-bootstrapper-1  Started                                                                                                                             0.7s 
 ✔ Container dss_sandbox-local-dss-scd-bootstrapper-1  Started                                                                                                                             0.7s 
 ✔ Container dss_sandbox-local-dss-core-service-1      Started                                                                                                                             0.9s 
build/dev/wait_for_local_dss.sh
Waiting for dss_sandbox_local-dss-dummy-oauth_1 container to start.................................................

**Expected behavior**
palyca-macbookpro1:monitoring palyca$ make start-locally
build/dev/run_locally.sh up -d
[+] Building 0.0s (0/0)                                                                                                                                                                         
[+] Running 5/5
 ✔ Container dss_sandbox-local-dss-dummy-oauth-1       Started                                                                                                                             0.3s 
 ✔ Container dss_sandbox-local-dss-crdb-1              Started                                                                                                                             0.4s 
 ✔ Container dss_sandbox-local-dss-scd-bootstrapper-1  Started                                                                                                                             0.6s 
 ✔ Container dss_sandbox-local-dss-rid-bootstrapper-1  Started                                                                                                                             0.6s 
 ✔ Container dss_sandbox-local-dss-core-service-1      Started                                                                                                                             0.8s 
build/dev/wait_for_local_dss.sh
Waiting for dss_sandbox-local-dss-core-service-1 to be available (currently starting)............
Local DSS instance is now available.

**Comment by BenjaminPelletier** [comment]
Migration to compose v2 was completed with #115
