### ISSUE TITLE
uss_qualifier reported a failure but I think my implementation is compliant (from slack discussion)

### ISSUE THREAD

**Issue by Dutzel** [interuss/monitoring#146]
Our attempt to handle the modification of injected flights is to cancel the old flight (including deletion in dss) and start a new approval process. This approach leads to failure of uss_qualifier tests, because the validation whether the flight has been published in dss is too late.

![image](https://github.com/interuss/monitoring/assets/17947422/f5c50d87-8958-4fcd-b72f-2e6aff12efe5)

[report-json.txt](https://github.com/interuss/monitoring/files/12250085/report-json.txt)

For further information feel free to take a look at the slack discussion from the InterUSS Project:
https://interuss.slack.com/archives/CNW4LF9NK/p1690298551395859

**Comment by mickmis** [comment]
FYI I will investigate this issue by the end of the week, please advise if this is more urgent.

**Comment by mickmis** [comment]
Changes described by @BenjaminPelletier to fix this issue are implemented in PR #154.

@Dutzel Once #154 is merged, or by testing out directly the code on the PR branch, could you confirm this solves your issue? Thanks!
