### ISSUE TITLE
Successful modification expected during conflict with high-priority flight

### ISSUE THREAD

**Issue by Dutzel** [interuss/monitoring#178]
Hello again :) We found a new qualifier issue that may not behave as expected.
By now we have 6/10 successful dss tests, the last 4 failed are "Attempt to modify planned flight in conflict" tests.

The issue we are currently investigating is the "Nominal planning: conflict with higher priority" scenario that only test USS1
(Tested USS -> uss1, Control USS -> uss1) **"Report-Json-Line: ~8360+"**

You expect uss1 to display ReadyToFly, but our system finds a ConflictWithFlight. The following image can help you understand this problem:

![image](https://github.com/interuss/monitoring/assets/17947422/2aff5da8-3c59-42b8-8620-30725f0ff4ea)

Upon further review of the issue, we still believe there is a conflict with the modified high priority flight.

Console Outputs:

`
uss_qualifier  | 2023-08-22 11:15:41.943 | INFO     | monitoring.uss_qualifier.scenarios.scenario:record_note:263 - Note: Tested USS -> uss1
uss_qualifier  | 2023-08-22 11:15:41.943 | INFO     | monitoring.uss_qualifier.scenarios.scenario:record_note:263 - Note: Control USS -> uss1
uss_qualifier  | 2023-08-22 11:15:41.952 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried GET http://host.docker.internal:8081/scdsc/v1/status -> 200
uss_qualifier  | 2023-08-22 11:15:41.953 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried GET http://host.docker.internal:8081/scdsc/v1/capabilities -> 200
uss_qualifier  | 2023-08-22 11:15:41.971 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8081/scdsc/v1/clear_area_requests -> 200
uss_qualifier  | 2023-08-22 11:15:41.995 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8081/scdsc/v1/clear_area_requests -> 200
uss_qualifier  | 2023-08-22 11:15:43.552 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/7dcd2d2b-47d1-48a4-a53e-314a66995187 -> 200
uss_qualifier  | 2023-08-22 11:15:45.113 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/47281e59-8146-4508-a748-5371a48c6ad8 -> 200
uss_qualifier  | 2023-08-22 11:15:45.113 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:45.126 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:45.145 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:45.174 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried GET http://host.docker.internal:8081/uss/api/uss/v1/operational_intents/7dcd2d2b-47d1-48a4-a53e-314a66995187 -> 200
uss_qualifier  | 2023-08-22 11:15:46.797 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried DELETE http://host.docker.internal:8081/scdsc/v1/flights/7dcd2d2b-47d1-48a4-a53e-314a66995187 -> 200
uss_qualifier  | 2023-08-22 11:15:48.358 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:15:48.366 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:48.396 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried GET http://host.docker.internal:8081/uss/api/uss/v1/operational_intents/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:15:49.963 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/2c7568ca-407c-468e-a016-d5faada31d9d -> 200
uss_qualifier  | 2023-08-22 11:15:51.539 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:15:51.549 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:51.549 | INFO     | monitoring.uss_qualifier.scenarios.scenario:record_note:263 - Note: uss1 -> Operational intent reference with ID 7992a772-d87f-4e58-8151-56bbd2d910e7 not found in DSS, instructed to skip test step.
uss_qualifier  | 2023-08-22 11:15:51.559 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:51.582 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried GET http://host.docker.internal:8081/uss/api/uss/v1/operational_intents/2c7568ca-407c-468e-a016-d5faada31d9d -> 200
uss_qualifier  | 2023-08-22 11:15:53.171 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:15:53.185 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:53.185 | INFO     | monitoring.uss_qualifier.scenarios.scenario:record_note:263 - Note: uss1 -> Operational intent reference with ID 7992a772-d87f-4e58-8151-56bbd2d910e7 not found in DSS, instructed to skip test step.
uss_qualifier  | 2023-08-22 11:15:54.777 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried DELETE http://host.docker.internal:8081/scdsc/v1/flights/2c7568ca-407c-468e-a016-d5faada31d9d -> 200
uss_qualifier  | 2023-08-22 11:15:56.330 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:15:56.339 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried POST http://host.docker.internal:8082/dss/v1/operational_intent_references/query -> 200
uss_qualifier  | 2023-08-22 11:15:56.358 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried GET http://host.docker.internal:8081/uss/api/uss/v1/operational_intents/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:15:57.938 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/ce723a80-a238-4e67-9030-53e81b1ea82c -> 200
uss_qualifier  | 2023-08-22 11:16:01.070 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/ce723a80-a238-4e67-9030-53e81b1ea82c -> 200
uss_qualifier  | 2023-08-22 11:16:02.629 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried PUT http://host.docker.internal:8081/scdsc/v1/flights/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:16:02.631 | WARNING  | monitoring.uss_qualifier.suites.suite:_print_failed_check:54 - New failed check:
uss_qualifier  |   details: uss1 indicated ConflictWithFlight rather than the expected ReadyToFly
uss_qualifier  |   documentation_url: https://github.com/interuss/monitoring/blob/0/monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_flight_intent.md#successful-modification-check
uss_qualifier  |   name: Successful modification
uss_qualifier  |   participants:
uss_qualifier  |   - uss1
uss_qualifier  |   query_report_timestamps:
uss_qualifier  |   - '2023-08-22T11:16:01.071008Z'
uss_qualifier  |   requirements:
uss_qualifier  |   - interuss.automated_testing.flight_planning.ExpectedBehavior
uss_qualifier  |   severity: High
uss_qualifier  |   summary: Flight unexpectedly ConflictWithFlight
uss_qualifier  |   timestamp: '2023-08-22T11:16:02.629732Z'
uss_qualifier  |
uss_qualifier  | 2023-08-22 11:16:04.255 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried DELETE http://host.docker.internal:8081/scdsc/v1/flights/ce723a80-a238-4e67-9030-53e81b1ea82c -> 200
uss_qualifier  | 2023-08-22 11:16:05.785 | DEBUG    | monitoring.uss_qualifier.scenarios.scenario:record_query:328 - Queried DELETE http://host.docker.internal:8081/scdsc/v1/flights/7992a772-d87f-4e58-8151-56bbd2d910e7 -> 200
uss_qualifier  | 2023-08-22 11:16:05.786 | WARNING  | monitoring.uss_qualifier.suites.suite:_run_test_scenario:129 - FAILURE for "Nominal planning: conflict with higher priority" scenario
`

[report-json.txt](https://github.com/interuss/monitoring/files/12409966/report-json.txt)

**Comment by BenjaminPelletier** [comment]
If I read `report-json.txt` correctly, it looks like the first failed check is on line 12644.  The check documentation is [here](https://github.com/interuss/monitoring/blob/0/monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_flight_intent.md#successful-modification-check) according to the report, but that documentation is not correct.  The current documentation says, "All flight intent data provided is correct and valid and free of conflict in space and time", but in fact flight 1 conflicts with flight 2.  The way this conflict came about is that flight 1 was created and activated (successfully), then higher-priority flight 2 was planned and activated over top of flight 1.  It is at this point the test step in question was executed.  This test step attempts to modify flight 1.  There is indeed a conflict with flight 2, however this is how SCD0030 reads:

```
5.4.2.6 A managing USS shall (SCD0030) verify that an
Activated operational intent that is modified while remaining in
the Activated state does not conflict with a higher priority
operational intent before the modification is executed unless
the conflict already existed at the time the modification was
initiated.
```

In this test step, the conflict already existed at the time the modification was initiated, therefore SCD0030 does not prohibit the modification.  A USS could satisfy all SCD requirements by simply refusing to plan under any conditions, but in order to be effectively tested by the InterUSS test suite, InterUSS expects that the USS, when presented with a situation where ASTM F3548-21 does not prohibit a planning action, will either successfully plan or else indicate that the planning action is [NotSupported](https://github.com/interuss/automated_testing_interfaces/blob/e6695316e38607343cd16ba31175eac21a1e46b3/scd/v1/scd.yaml#L449) -- it should not indicate Rejected or ConflictWithFlight since ASTM F3548-21 does not prohibit that planning action.

InterUSS will improve the test documentation to more clearly indicate the above.

**Comment by Dutzel** [comment]
Thanks again for the reply :)
We have discussed the problem in our team and we are facing some problems here. One problem is that we are in exchange with DFS (German air safety) and various authorities who are very concerned about the risks of drone flights. It might be a challenge to explain to them why it is necessary to send a readyToFly response when there is an actual conflict.

Have you thought of adding an additional status for this case?

Also, we have a small problem at this point because our USS does not allow UAS to change their flight intends. This means that new flights will result in a cancellation of the old flight and a new approval request for the new flight. This is also our rule for the activated state, since we interpret a changed flight intention as a deactivation that triggers a new approval process.
So in this case of the situation we answer correctly that we ve spottet a conflict.

**Comment by BenjaminPelletier** [comment]
I think my tentative suggestion would probably be to return NotSupported in the case where a user attempts to replan in the presence of an existing conflict without resolving that conflict -- the rationale would be that planning a new flight there wouldn't be allowed and your system only supports "changing" flight by ending the existing flight and creating a new one (therefore, your system doesn't support actually changing a flight).  I don't know if the test currently accepts NotSupported as a response, but I think it probably should.

**Comment by Dutzel** [comment]
I just saw the updated scd.yaml. So yes, NotSupported seems to be a reasonable answer :) Thank you!

Today I updated the project to the latest monitoring version + the scd.yaml. As far as I can see, NotSupported is not currently a valid response for this case.

Here is my updated report file:


[report-json.txt](https://github.com/interuss/monitoring/files/12486961/report-json.txt)

**Comment by Dutzel** [comment]
@BenjaminPelletier 
I tried to run with the latest version again, but I still have the issue, that NotSupported is still an invalid response for the qualifier. Or am I doing anything wrong??

`
uss_qualifier  | 2023-09-08 08:22:47.551 | WARNING  | monitoring.uss_qualifier.suites.suite:_print_failed_check:54 - New failed check:
uss_qualifier  |   details: "Inject flight response from http://host.docker.internal:8081/scdsc/v1/flights/3bed79e4-a3de-4afa-8b57-bb04d1121618\
uss_qualifier  |     \ could not be decoded: 'NotSupported' is not a valid InjectFlightResult\n\nStack\
uss_qualifier  |     \ trace:\nTraceback (most recent call last):\n  File \"/app/monitoring/uss_qualifier/resources/flight_planning/flight_planner.py\"\
uss_qualifier  |     , line 100, in request_flight\n    result = ImplicitDict.parse(\n  File \"/usr/local/lib/python3.8/site-packages/implicitdict/__init__.py\"\
uss_qualifier  |     , line 87, in parse\n    kwargs[key] = _parse_value(value, hints[key])\n  File \"\
uss_qualifier  |     /usr/local/lib/python3.8/site-packages/implicitdict/__init__.py\", line 199, in\
uss_qualifier  |     \ _parse_value\n    return value_type(value) if value_type else value\n  File \"\
uss_qualifier  |     /usr/local/lib/python3.8/enum.py\", line 339, in __call__\n    return cls.__new__(cls,\
uss_qualifier  |     \ value)\n  File \"/usr/local/lib/python3.8/enum.py\", line 663, in __new__\n  \
uss_qualifier  |     \  raise ve_exc\nValueError: 'NotSupported' is not a valid InjectFlightResult\n\n\
uss_qualifier  |     During handling of the above exception, another exception occurred:\n\nTraceback\
uss_qualifier  |     \ (most recent call last):\n  File \"/app/monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py\"\
uss_qualifier  |     , line 376, in submit_flight_intent\n    resp, query, flight_id = flight_planner.request_flight(\n\
uss_qualifier  |     \  File \"/app/monitoring/uss_qualifier/resources/flight_planning/flight_planner.py\"\
uss_qualifier  |     , line 104, in request_flight\n    raise QueryError(\nmonitoring.monitorlib.fetch.QueryError:\
uss_qualifier  |     \ Inject flight response from http://host.docker.internal:8081/scdsc/v1/flights/3bed79e4-a3de-4afa-8b57-bb04d1121618\
uss_qualifier  |     \ could not be decoded: 'NotSupported' is not a valid InjectFlightResult\n"
uss_qualifier  |   documentation_url: https://github.com/interuss/monitoring/blob/0/monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_flight_intent.md#successful-modification-check
uss_qualifier  |   name: Successful modification
uss_qualifier  |   participants:
uss_qualifier  |   - uss1
uss_qualifier  |   query_report_timestamps:
uss_qualifier  |   - '2023-09-08T08:22:47.526181Z'
uss_qualifier  |   requirements:
uss_qualifier  |   - interuss.automated_testing.flight_planning.ExpectedBehavior
uss_qualifier  |   severity: High
uss_qualifier  |   summary: 'Error from uss1 when attempting to submit a flight intent (flight ID: 3bed79e4-a3de-4afa-8b57-bb04d1121618)'
uss_qualifier  |   timestamp: '2023-09-08T08:22:47.546931Z'
`

**Comment by BenjaminPelletier** [comment]
We're currently looking to address this issue the week of Sept 18.  Please let us know if you have a more urgent need and might be able to help with the change -- I can help with the first PR
