### ISSUE TITLE
uss_qualifier should not activate flights early

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#217]
**report.json is not attached because**
This is a general problem where a specific report.json does not provide useful information.

**Test check**
[Successful activation](https://github.com/interuss/monitoring/blob/notional-faa-tests/monitoring/uss_qualifier/configurations/dev/laanc.yaml) for [Activate flight 1 test step](https://github.com/interuss/monitoring/blob/notional-faa-tests/monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md#attempt-to-modify-activated-flight-in-conflict-test-case), among others

**Difference from expected behavior**
Currently in ASTM F3548 tests, uss_qualifier generally tries to activate flights whose volumes start in the future and expects this activation to succeed.  In fact, a user claiming to start using the airspace prior to the start of their reservation volumes should either be rejected or have their operational intent placed in Nonconforming (though the latter option is unavailable to USSs performing only SCD).

When uss_qualifier needs to activate flights, uss_qualifier should require test configurations to provide flight data whose volumes start a reasonably small amount of time after the test step begins, and then uss_qualifier should wait to attempt to activate those flights until the wall clock is within the defined volumes.  This will likely suggest rethinking the structure of some existing tests to maximize efficiency (e.g., do all the planning before waiting just once for the activation time to elapse, then do the activation actions at that point).

**Additional context**
This was not a problem when uss_qualifier was exercised in a SUSI trial because only non-Activated flights were used.  Testing against a real system that correctly rejects early activation requests revealed the issue.

**Comment by mickmis** [comment]
Would it be acceptable to put the constraint on the provided intents that they all must be "now"? I.e. their time start is before the reference time (module planning time), and of course their end time leaves sufficient time for the test to be executed. 
Then we modify the existing tests / test data to rely on some other dimension of the 4D volume to create conflicts (e.g. altitude).
With this we are assured all intents can be activated at any time during the execution of the scenario, and we avoid refactoring the scenarios steps.
WDYT?
