### ISSUE TITLE
Phantom flight injection request in CI

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#230]
**Describe the bug**
During CI, a mock_uss instance appeared to receive a request to inject a flight that didn't come from a reported query of uss_qualifier.

**To reproduce**
* See [this CI run](https://github.com/interuss/monitoring/actions/runs/6353175530?pr=226).  I've also more permanently uploaded the two relevant artifacts to this issue:
    * [monitoring-test-uss_qualifier-logs.zip](https://github.com/interuss/monitoring/files/12794281/monitoring-test-uss_qualifier-logs.zip)
    * [monitoring-test-uss_qualifier-reports.zip](https://github.com/interuss/monitoring/files/12794283/monitoring-test-uss_qualifier-reports.zip)
* Observe that the failed check on line 70364 of report_uspace.json was that uss1 was not supposed to share an operational intent, but a new operational intent with ID f1cd822e-0158-4063-93d4-e5d1d79a012c was found.  The two attached queries support this -- the DSS shows that new op intent ID the second POST query but not the first.
* Note that the "before" query was initiated at 14:50:35.97 and the "after" query was reported at 14:50:36.26
* On line 2178 of local_infra.log, note that operational intent reference f1cd822e-0158-4063-93d4-e5d1d79a012c belongs to uss2 and was created at 14:50:36.14
* In mock_uss_scdsc_b.log, note that the flight injection ID active near this timestamp is 20639505-2e10-47c9-9280-776eba3ed190 (and line 2483 matches well to op intent f1cd822e being created in the DSS)
* Searching in report_uspace.json, there are report elements for flight 20639505-2e10-47c9-9280-776eba3ed190, but these elements begin at 14:50:03.45 and end at 14:50:18.49 -- there are no logged queries from uss_qualifier for flight 20639505 at the relevant time

**Difference from expected behavior**
I would expect that the only uss_qualifier would be issuing flight injection requests, so the injection request mock_uss_scdsc_b received at 14:50:35.89 should be in the queries in report_uspace.json.  However, the request to inject flight 20639505-2e10-47c9-9280-776eba3ed190 circa 14:50:36 does not appear in that report.  Generally, I would not expect this flight injection request to uss2 to occur at this time at all.

**Possible solution**
It seems like the later request to inject flight 20639505-2e10-47c9-9280-776eba3ed190 into uss2 may have been a spurious repeat of an earlier request -- adding a request_id to requests (and rejecting requests that have already been fulfilled) may address this issue.  However, the logged data does not contain enough information to definitively determine whether this was actually the cause as we do not yet have or log request IDs.

**System on which behavior was encountered**
GitHub CI runner

**Codebase information**
I am confused about this one.  The commit that should have been tested was bef61348db12f0656474e673a13bb98766f48c45 -- that is the commit labeled in GitHub with the red X linking to the CI run above.  However, the uss_qualifier reports indicate a commit hash of 248f1ad1ceebfc5773a5df76a2b36b23a22e2517.

**Additional context**
Simply rerunning the CI resolved the problem, meaning this issue only occurs occasionally.

**Comment by mickmis** [comment]
> It seems like the later request to inject flight 20639505-2e10-47c9-9280-776eba3ed190 into uss2 may have been a spurious repeat of an earlier request -- adding a request_id to requests (and rejecting requests that have already been fulfilled) may address this issue. However, the logged data does not contain enough information to definitively determine whether this was actually the cause as we do not yet have or log request IDs.

That would be consistent with the CI timeout issues. IIRC those requests are retried up to 3 times before actually erroring out with a timeout. I have seen quite a few times in successful CI runs timed out requests that were successfully retried thus not failing the CI.

**Comment by mickmis** [comment]
> The commit that should have been tested was https://github.com/interuss/monitoring/commit/bef61348db12f0656474e673a13bb98766f48c45 -- that is the commit labeled in GitHub with the red X linking to the CI run above. However, the uss_qualifier reports indicate a commit hash of https://github.com/interuss/monitoring/commit/248f1ad1ceebfc5773a5df76a2b36b23a22e2517.

Not sure why, and if it is actually an issue or not, but that seems to be on the GitHub Actions side, since the "Set up job" logs indicate checkout of https://github.com/interuss/monitoring/commit/248f1ad1ceebfc5773a5df76a2b36b23a22e2517 :
```
Uses: interuss/monitoring/.github/workflows/monitoring-test.yml@refs/pull/226/merge (248f1ad1ceebfc5773a5df76a2b36b23a22e2517)
```
