### ISSUE TITLE
Update Flask to v2

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#329]
**Is your feature request related to a problem? Please describe.**
The older version of Flask we're using has security vulnerabilities.  Because mock_uss should be used only in test systems, these vulnerabilities are not high-impact, but we should still follow best security practices when possible.

**Describe the solution you'd like**
Update Flask to the latest version (2.2.5, as of the creation of this issue).  Note that multiple other dependencies should/must be updated at the same time -- see notes in requirements.txt linking to issues and noting Flask compatibility issues.

**Additional context**
Dependabot was unable to make this change automatically (see #325).

**Comment by Shastick** [comment]
Note for later: we might want to start pinning all dependencies (incl. transitive ones) using something like [pip-tools](https://github.com/jazzband/pip-tools).

In a nutshell, we'd have our direct (or first-level) dependencies defined in a `requirements.in` file, and `pip-compile` it to a `requirements.txt` file that would contain the exhaustive list of our dependencies.
