### ISSUE TITLE
"Initial" and "subsequent" RID observation queries not correctly categorized

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#343]
**report.json is not attached because**
This screenshot should be sufficiently illustrative:
<img width="1489" alt="Screenshot 2023-11-14 at 12 02 12 PM" src="https://github.com/interuss/monitoring/assets/11224086/d6c1c2e0-39f1-46c7-adc5-0a905b46bc8a">

**Test check**
See screenshot

**Difference from expected behavior**
The note below the check pictured above indicates that the 95th and 99th percentiles of "initial" and "subsequent" queries match to the precision displayed.  This seems to strongly suggest that the same set of queries were considered both "initial" and "subsequent".  A given query should be exclusively categorized as either "initial" or "subsequent"; a single query should never be categorized as both.  Since it seems that every query is being categorized as both "initial" and "subsequent", it seems like something needs to be fixed.

**Additional context**
This relates to ASTM F3411-22a NET0440.

**Comment by Shastick** [comment]
Taking this on. At first glance I did not find a simple bug where we'd have mistakenly used the same collection: I'll look deeper into the details later today.

**Comment by Shastick** [comment]
Spent a bit of time and did not find the root-cause: https://github.com/interuss/monitoring/pull/345 shows that it's not a trivial mistake either, I'll wait for @mickmis to have a quick look for the case where I missed something obvious.

**Comment by mickmis** [comment]
Looks like that is because queries are added twice in the list of queries to consider:
https://github.com/interuss/monitoring/blob/7840f3dbaa5cc6df816abf1ada3077d03194fd72/monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py#L80-L94

**Comment by Shastick** [comment]
I believe this was fixed by #345, please reopen if this is incorrect.
