### ISSUE TITLE
Test error when activating low-priority conflicted flight

### ISSUE THREAD

**Issue by hsrodriguez** [interuss/monitoring#387]
[Report File](https://github.com/interuss/monitoring/files/13562573/report.json)

**Test check**
Test *Validate flight 1 not activated* on report line 2636

**Difference from expected behavior**
The [test step](https://github.com/interuss/monitoring/blob/ca23714432a3ce36a992bfb8db42eaefdf4b448f/monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.md#validate-flight-1-not-activated-test-step) says *Flight 1 should not have been modified (because the USS kept the original accepted request)*. The reports says that the operation `3f7e33ff-5a6f-4321-ba47-d95360c0a715` was version 1 before and after the planning request that is what is expected in the test. 
The test is still failing because the operation was not found in the DSS and since the operation is in conflict, it should not be shared in the DSS

**Comment by BenjaminPelletier** [comment]
@mickmis I'm familiar with this issue so please let me know if anything isn't clear.  The sequence view artifact can be generated from the report attached above with [`make_artifacts.sh`](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/make_artifacts.sh) and I suspect we'll be doing that a fair amount going forward.

In addition to the above, the failed check description in the report is confusing -- it says "_USS uss1 was supposed to have shared a new operational intent with the DSS, but no matching operational intent references were found in the DSS in the area of the flight intent_" whereas the expectation per [test step description](https://github.com/interuss/monitoring/blob/ca23714432a3ce36a992bfb8db42eaefdf4b448f/monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.md#validate-flight-1-not-activated-test-step) is that the flight either isn't modified or is removed, and the former option (wasn't modified) actually occurred in the provided report.

**Comment by mickmis** [comment]
I think I found the issue, a missed corner-case in `OpIntentValidator.expect_shared`. I am writing a fix.

> In addition to the above, the failed check description in the report is confusing

If I'm correct about my hypothesis and that this is basically a bug in the test framework (and not in the scenario), I think we can ignore the fact that a wrong check description was included, as that should be fixed by fixing the bug.

**Comment by hsrodriguez** [comment]
Thanks @mickmis, I think is working as expected now. Closing the issue.
