### ISSUE TITLE
Validation error on scenario scenarios.astm.utm.DownUSS

### ISSUE THREAD

**Issue by hsrodriguez** [interuss/monitoring#408]
While running the scenario `scenarios.astm.utm.DownUSS`. I am getting an error that says `uss1 indicated InjectFlightResponseResult.Rejected rather than the expected ConflictWithFlight or Planned or Rejected`. 

The response includes the status of Rejected. The error can be seen in the 
[report.json](https://github.com/interuss/monitoring/files/13678875/report-DownUSS.json) line 6774

**Comment by BenjaminPelletier** [comment]
@mickmis could you take a look?  It seems like this sounds similar to #398

**Comment by mickmis** [comment]
@BenjaminPelletier @hsrodriguez I confirm this is the same issue than #398 and #409 with the twist that it looks like @hsrodriguez ran the test with the "stop fast" configuration, thus the "warning" low severity issue got upgraded to critical.

I'd propose that the outcome of this issue (#408) is that we make low severity issues to not be upgraded to critical even when the "stop fast" configuration is enabled. The rest is covered by #398 and #409.
