### ISSUE TITLE
Annotate nearly all uss_qualifier queries with participant and type

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#431]
**Is your feature request related to a problem? Please describe.**
Currently, we issue a large number of queries that are not annotated with the query type, and some that are not annotated with the participant affected.  This missing information makes it so we cannot use these queries in aggregate performance checks or other future analysis that may be useful to perform.

**Describe the solution you'd like**
Add a console warning (instead of debug message) whenever `record_query` is called for a query where `participant_id` or `query_type` is not specified.  Then, try to eliminate as many warnings as practical.  This should generally be done at the lowest level practical -- e.g., query type assignment should happen inside a routine called `fetch.isas` rather than being assigned after the fact in the calling routine.

**Describe alternatives you've considered**
Participant and query type could be assigned in bulk at the conclusion of lots of operations, but I think this would be less robust because there may be multiple consumers of the information and it will be unclear whether that patch has been applied at the pont where the consumer has interest.  It seems far more robust to annotate the information at the original point where it is available.

**Comment by Shastick** [comment]
Picking this up.

Observation:

> Participant and query type could be assigned in bulk at the conclusion of lots of operations, but I think this would be less robust because there may be multiple consumers of the information and it will be unclear whether that patch has been applied at the point where the consumer has interest. It seems far more robust to annotate the information at the original point where it is available.

Indeed, being able to rely on the type and participant_id at any time can be helpful in scenarios, so it feels worth it to properly set these immediately.
