### ISSUE TITLE
Check "Operational intent not shared" does not exist in DownUSS scenario

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#440]
**report.json is not attached because**
Redacted sequence view page attached instead: 
[s4.html.zip](https://github.com/interuss/monitoring/files/13747298/s4.html.zip)

**Test check**
uss_qualifier error message:

_Test scenario `monitoring.uss_qualifier.scenarios.astm.utm.off_nominal_planning.down_uss.DownUSS` was instructed to prepare to record outcome for check "Operational intent not shared" during test step "Validate Flight 1 status" during test case "Plan Flight 1 in conflict with accepted operational intent managed by down USS", but that check is not declared in documentation; declared checks are: DSS responses, Operational intent shared correctly, Operational intent for active flight not deleted, Operational intent details retrievable, Operational intent details data format, Correct operational intent details, Off-nominal volumes, Vertices_

**Difference from expected behavior**
I would expect all feasible checks to be documented (directly or via appropriate links)

**Comment by mickmis** [comment]
It looks like the issue have always been there actually. I think it didn't bubble up earlier because this execution path is not covered by the CI. I am making a fix, this should not be very complex.

**Comment by mickmis** [comment]
@BenjaminPelletier could you confirm the issue was fixed?

**Comment by BenjaminPelletier** [comment]
I think we can assume #441 fixed this issue unless we discover otherwise.
