### ISSUE TITLE
OpIntentValidator raises exception before recording query

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#458]
**report.json is not attached because**
s2_redacted.html attached instead.  Codebase version used for test was 51ef12212b91387c95e3293d54d0f60bfb087cc8.
[s2_redacted.html.zip](https://github.com/interuss/monitoring/files/13835293/s2_redacted.html.zip)

**Test check**
None; scenario effectively crashes when it is not at a check.

**Difference from expected behavior**
uss_qualifier should never have exceptions to report to the user under nominal circumstances.  If exceptions are raised under expected conditions (e.g., raising QueryError), they should be caught and applied to a check or normal flow control logic.  In this case, failure to do so made it so the query critical to identifying and resolving the problem (the call to get op intent details from the USS under test) was not recoded in the report.

**Additional context**
This also affects OpIntentValidator, so we probably want to finish merging #428 before addressing this issue.

**Comment by BenjaminPelletier** [comment]
Another example
[s2_redacted.html.zip](https://github.com/interuss/monitoring/files/13836283/s2_redacted.html.zip)

**Comment by mickmis** [comment]
When all the PRs that mentioned this issue are merged (at the time of writing this #501, 502 and #503 are still open) I think this issue can be closed as those changes ensure that queries are recorded when some functions of [DSSInstance](https://github.com/interuss/monitoring/blob/7add979b2c44ca2eab9976cea9901e6ae1c38178/monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py) are used.
Now the same issue is very probably present in other parts of the codebase as the error handling for querying USSes/DSS is quite inconsistent.
I believe the approach I used in `DSSInstance` enables flexibility in the error handling while being able to ensure queries are recorder, at the price of a slightly heavier call site. It could probably be extended to other calls but I'm not sure of what kind of priorities this would have now.

**Comment by BenjaminPelletier** [comment]
All mentioned PRs are merged.  We'll keep in mind error resilience as we develop and improve, but I believe this specific issue can be closed.
