### ISSUE TITLE
GEN0100 and GEN0105 uss_qualifier checks to verify ASTM F3548-21

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#468]
As part of #274, we should check GEN0100 and GEN0105.  Presumably these requirements will be checked together since a good way of measuring time synchronization (GEN0100) is via timestamps (GEN0105).

Possible approach 1:

When op intent details change (creation or update), note when the change was made.  If volumes end time is before time change was made, USS may be [violating](https://github.com/astm-utm/Protocol/blob/d26d3222b9816a5bc90d00287c9746c4255f8f0d/utm.yaml#L1040) USS0105, or it may be violating GEN0100, or it may be violating GEN0105.

Possible approach 2 (not mutually exclusive):

If/when we obtain [log data](https://github.com/astm-utm/Protocol/blob/F3548-21/utm.yaml#L1392), compare timestamps for when we know certain events occurred to when they are indicated in the logs<sup>[1](https://github.com/astm-utm/Protocol/blob/F3548-21/utm.yaml#L1490), [2](https://github.com/astm-utm/Protocol/blob/F3548-21/utm.yaml#L1498), [3](https://github.com/astm-utm/Protocol/blob/F3548-21/utm.yaml#L1574)</sup>

**Comment by Shastick** [comment]
Discussing the topic with @mickmis and @barroco, we were wondering if this might not require adding a new endpoint, depending how strictly we want to test the requirements:

The gist of our discussion:

- do we do _loose_ testing by any means (direct or indirect) available?
  - indirect: 
    - your suggestion is such an approach.
    - possibly we can make assumptions on the default values used by the DSS when we omit to specify the start time of a volume
    - we could add an endpoint returning the current time of the DSS
    - we could update some/all endpoints for them to include the current time of the DSS
- do we do _strict_ testing, by checking that anything or most of the entities that get timestamped by the DSS receive the correct timestamp? A very strict interpretation of GEN0105 would probably require that

We also conclude that logs will likely contain what we need to cover GEN0100/0105, but these won't be available for the initial MVP so we need an alternative.

(If this requires more discussion/editing we can take it to a separate design doc)

**Comment by mickmis** [comment]
Implemented in #555
