### ISSUE TITLE
Add checks to ensure the DSS response is correctly formatted and contains all require contents

### ISSUE THREAD

**Issue by charlie-pisuraj** [interuss/monitoring#5]
We need to add test cases to ensure that the DSS response contains all the required fields based on the minimum specs and that its correct formatted.

**Comment by Shastick** [comment]
This is taken care of by multiple `*_validator.py` (such as the [ISAValidator](https://github.com/interuss/monitoring/blob/5cb83ab7174453e6f323957c1265f961b3142b2e/monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validator.py#L17) in netrid or the [OIRValidator](https://github.com/interuss/monitoring/blob/c2659bf10d9db9ae78e1f2341aa8b9ffb5fa7ed0/monitoring/uss_qualifier/scenarios/astm/utm/dss/validators/oir_validator.py#L27) in scd – all entities have their own). 

These validators are used by multiple scenarios. 

If we missed anything, please either open a new issue or re-open another one.
