### ISSUE TITLE
DSS0210,A2-7-2,3,a Op. Intent Ref. can be deleted from any instance of a DSS deployment

### ISSUE THREAD

**Issue by Shastick** [interuss/monitoring#540]
**Is your feature request related to a problem? Please describe.**
Splits out the individual requirement for DSS0210,A2-7-2,3a from #434

**Describe the solution you'd like**

DSS0210,A2-7-2,3 (a & b) mandates:

> Tests must demonstrate that an entity reference can be deleted on any DSS instance in the DSS pool and the deletion is reflected on all DSS instances in the DSS pool using queryOperationalIntentReferences, getOperationalIntentReference, queryConstraintReferences, and getConstraintReference

We want this requirement covered for Operaional Intent references.

**context**

This should probably wait on #573 to be done, as this issue could be solved by expanding the OIR sync testing scenario.

**Comment by mickmis** [comment]
Implemented in #613
