### ISSUE TITLE
"Operational intent for active flight not deleted" never checked

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#564]
**report.json is not attached because**
The issue is observable with [the current CI U-space test report](https://interuss.github.io/monitoring/artifacts/uss_qualifier/reports/uspace/report.json).

**Test check**
[Operational intent for active flight not deleted](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md#-operational-intent-for-active-flight-not-deleted-check)

**Difference from expected behavior**
This check is apparently never performed -- it does not seem to appear anywhere in report.json for our most comprehensive F3548-21 test configuration (U-space) even though it is the only check for the FlightCoveredByOperationalIntent requirement and many test steps [claim](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/suites/astm/utm/f3548_21.md) that they may perform this check.  I would expect, at a minimum, this check to be performed at least sometimes.  I would also expect that this check is only mentioned in test steps in which it is at least sometimes performed, though that fix is slightly less urgent.

**Additional context**
This is a screenshot from a tested requirements artifact showing the test steps that claim a check related to FlightCoveredByOperationalIntent may be performed, and then the check is actually performed in none of them (though note that not all of these scenarios was run in the particular configuration that generated that report).

![Screenshot 2024-03-18 at 8 23 31 PM](https://github.com/interuss/monitoring/assets/11224086/09b3c374-0250-4b9d-b43a-221a79e99107)

**Comment by mickmis** [comment]
I will have a look at it. I'm assuming that this is part of the Q1 deadline?
