### ISSUE TITLE
ReceiveNotificationsForAwareness queries DSS for wrong time range

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#649]
**report.json is not attached because**
See sequence view test step instead:

[s63.html.zip](https://github.com/interuss/monitoring/files/15056370/s63.html.zip)

**Test check**
[Operational intent shared correctly check](https://github.com/interuss/monitoring/blob/befe56ff837d3f4d449e0e18d66d917a79db03a1/monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md#operational-intent-shared-correctly-check) in [Tested_uss plans and activates Flight 1 test step](https://github.com/interuss/monitoring/blob/befe56ff837d3f4d449e0e18d66d917a79db03a1/monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/receive_notifications_for_awareness/receive_notifications_for_awareness.md#tested_uss-plans-and-activates-flight-1-test-step)

**Difference from expected behavior**
uss_qualifier claims there is no operational intent corresponding to the planned flight, however the time range queried in the DSS (in both e3 and e8) does not match (and, in fact, does not even intersect) the time range requested for the flight (see e5).

**Comment by Shastick** [comment]
From a first look: it seems that the [extents](https://github.com/interuss/monitoring/blob/e29f1b847402d5061575f098e2695cd419b20a44/monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/receive_notifications_for_awareness/receive_notifications_for_awareness.py#L179) used in the `OpIntentValidator` don't include the extent of `flight_1_planned`, and either that flight is missing from the [computation of the aggregated extents](https://github.com/interuss/monitoring/blob/e29f1b847402d5061575f098e2695cd419b20a44/monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/receive_notifications_for_awareness/receive_notifications_for_awareness.py#L128) or this computation has a bug.

**Comment by Shastick** [comment]
The problem (very likely) seems to arise from the fact that, in scenarios that consume flight intents, we compute the overall extents that will be used to query the DSS at scenario instantiation time, while the start and end times of flight intents that will effectively be created are resolved when the relevant test step is executed.

I'll draft a PR that will tentatively remove all pre-computed extents, and compute them on the fly base on the properly resolved flight intents.

**Comment by Shastick** [comment]
As far as I can tell this was addressed specifically by #652 and more generally by the migration to the new flight info template.
