### ISSUE TITLE
Down USS scenarios do not verify area is clear

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#670]
**report.json is not attached because**
Simple description should suffice; see below.

**Test check**
* [Operational intent successfully created](https://github.com/interuss/monitoring/blob/13d0c46305fdaa435b5e0ab9ea58121fc033a5f7/monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md#operational-intent-successfully-created-check)
* The [same check in DownUSSEqualPriorityNotPermitted](https://github.com/interuss/monitoring/blob/13d0c46305fdaa435b5e0ab9ea58121fc033a5f7/monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.md#virtual-uss-creates-conflicting-operational-intent-test-step)

**Difference from expected behavior**
When an operational intent not managed by the account used by uss_qualifier is present in the test area for scenarios.astm.utm.DownUSS or scenarios.astm.utm.DownUSSEqualPriorityNotPermitted, the test scenario will fail because the attempt to write an operational intent will fail 409 to the DSS because no OVNs are provided.

- [x] First, DownUSSEqualPriorityNotPermitted actually raises an uncaught exception because its checks do not have severity indicated in documentation -- severities should be added to documentation.
- [x] Second, both scenarios should check whether the area is clear before proceeding.  If they can function in the presence of other operational intents, then the OVNs for those operational intents should be acquired and provided when performing op intent operations.  If they cannot function in the presence of other operational intents, then a check for that condition should fail.  The failure should not be attributed to the participant providing the DSS instance.

**Comment by Shastick** [comment]
This should be handled by #671 and #672. If DownUSS should be allowed to run even if the are is non empty (contrary to DownUSSEqualPriorityNotPermitted, that should in theory be possible), we should probably open another issue with a lower priority.
