### ISSUE TITLE
Fix requirement annotation for telemetry check

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#699]
**Observed behavior**
The requirement indicated in the test check below is SCD0100, but that requirement is not applicable to the check.

**Test check**
[Operational intent telemetry retrievable](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md#-operational-intent-telemetry-retrievable-check)

**Difference from expected behavior**
The requirement applicable to this check is actually CMSA0330.  SCD0100 should be changed to CMSA0330.

**Additional context**
This observation was made in FAA/NASA feedback.

**Comment by mickmis** [comment]
I have two points to raise:

1. From what I can recall, to test SCD0100 we needed a way to infer whether the USS has the CMSA role or not. We implemented that by querying for telemetry, and if there is any error we assume that this indicates that the USS does not have the CMSA role. That's indeed quite flaky, so I agree it makes sense to change that. However then we won't test anymore SCD0100, so what do we do in that regard? We should probably at least open a separate issue to track this, or implement a separate test.
2. Isn't CMSA0330 a performance requirement? It specifies the condition *if the most recent position information is available for the operational intent*: as such my understanding is that if the telemetry is not returned this does not mean that CMSA0330 failed. And I'm not sure we can ensure that the USS does have the telemetry available, or can we?

**Comment by BenjaminPelletier** [comment]
> That's indeed quite flaky, so I agree it makes sense to change that.

Yeah, I agree.  As our sophistication/rigor/experience increases, we can update things like this.

> then we won't test anymore SCD0100, so what do we do in that regard?

The requirement is that a USS not performing CMSA not transition an op intent to Nonconforming or Contingent.  Fortunately, we (relatively) recently added [a scenario](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_state_transitions.md) which verifies that the DSS enforces this requirement programmatically according to the API.  Therefore, like [OPIN0035](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_access_control.md#-non-owning-credentials-cannot-modify-operational-intent-check), we can allow anyone [annotated as using a DSS instance verified as enforcing compliance to this requirement](https://github.com/interuss/monitoring/blob/58d636e06c5f05011bc668aeee85fc5d4e439694/monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_access_control.py#L441) to have verified compliance to this requirement as well.  It looks like that existing scenario for SCD0100-via-DSS **does need to be adjusted** to allow the DSS's user_participant_ids to take credit for verification of SCD0100 via DSS enforcement.

> Isn't CMSA0330 a performance requirement?

Yes, but it also requires some non-performance validity -- a USS performing CMSA should either respond 200 or 412 for this telemetry request when its op intent is Nonconforming or Contingent.  Any of the other response codes would be invalid in this situation.

However, I don't think it belongs in our general-purpose check for validating a shared operational intent.  Instead, when we build CMSA test scenarios, we'll know when this endpoint should be responding 200 or 412 and perform the check only in those cases.

**Comment by BenjaminPelletier** [comment]
That seems good to me, except I think I would execute in order 2, 1, 3.  If we did 1 first, that would cause us to regress on our ability to fully verify participants for SCD0100 until we did 2.

**Comment by mickmis** [comment]
> That seems good to me, except I think I would execute in order 2, 1, 3. If we did 1 first, that would cause us to regress on our ability to fully verify participants for SCD0100 until we did 2.

Alright, then I will put #715 in draft until I'm done with 2.

**Comment by Shastick** [comment]
@mickmis is this issue still relevant or was it fully addressed by #716?

**Comment by mickmis** [comment]
IMO this issue was addressed, closing it. Thanks for the ping :)
