### ISSUE TITLE
[build] pip install fails when building the image

### ISSUE THREAD

**Issue by barroco** [interuss/monitoring#768]
**Describe the bug**
As reported by [Jason on Slack](https://interuss.slack.com/archives/CNW4LF9NK/p1725472654205109) and [reproduced by the CI on the latest master commit](https://github.com/interuss/monitoring/actions/runs/10580955837/job/29687312692#step:4:1370) (https://github.com/interuss/monitoring/commit/d49267437325a47e0e329ebf240e271a0e035e51), the docker image build fails at step `[ 6/12] RUN pip install -r /app/monitoring/requirements.txt && rm -rf __pycache__` with the following error:
```
#11 17.61   Downloading zope.interface-6.3-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (255 kB)
#11 17.97 Collecting setuptools>=3.0 (from gunicorn==20.1.0->-r /app/monitoring/requirements.txt (line 690))
#11 18.11 ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
#11 18.11     setuptools>=3.0 from https://files.pythonhosted.org/packages/48/f3/e30ee63caefa90716afdffd7d9ae959cd8d0dbd2d0a0eb9fe1d73ddf806b/setuptools-74.1.1-py3-none-any.whl (from gunicorn==20.1.0->-r /app/monitoring/requirements.txt (line 690))
#11 ERROR: process "/bin/sh -c pip install -r /app/monitoring/requirements.txt && rm -rf __pycache__" did not complete successfully: exit code: 1
```
See [logs for complete stack trace](https://github.com/interuss/monitoring/actions/runs/10580955837/job/29687312692#step:4:1370).

**Comment by Shastick** [comment]
This particular issue has been addressed for now.
