### ISSUE TITLE
Data validation scenario behaves incorrectly under mock_uss failure

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#772]
**Observed behavior**
USS under test fails [Awareness of relevant operational intents scenario](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/receive_notifications_for_awareness/receive_notifications_for_awareness.md) because mock_uss has a pre-existing operational intent with intentionally-incorrect data ([priority = 1.2](https://github.com/interuss/monitoring/blob/39dbd67a2d539985e892b35449405ffb94e322fa/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py#L263)) from the previous scenario, [Data Validation of GET operational intents by USS](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md), and the USS under test (correctly) cannot parse this invalid operational intent.

**Test check**
N/A

**Difference from expected behavior**
1. [Data Validation of GET operational intents by USS](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md) should clean up any flights/operational intents that could be in existence during the cleanup phase, but instead doesn't clean up if [the flight intent creation by mock_uss](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md#mock_uss-plans-flight-2-sharing-invalid-operational-intent-data-test-step) returns 500 even though the flight is successfully created.
    a. We should trigger the flight clean up upon scenario failure even if the flight creation call returns 500 (because the flight might have been created before the error was encountered)
2. The 500 error is being caused by attempting to access an ImplicitDict field on an object that is a mere dict and not an ImplicitDict type ([the `.reference` field access](https://github.com/interuss/monitoring/blob/39dbd67a2d539985e892b35449405ffb94e322fa/monitoring/mock_uss/f3548v21/flight_planning.py#L534)) -- we should not attempt to treat a plain dict like an ImplicitDict type
    a. The underlying issue is that the addition of [the `parse_result` argument](https://github.com/interuss/monitoring/blob/39dbd67a2d539985e892b35449405ffb94e322fa/monitoring/uss_qualifier/resources/overrides.py#L10) broke the type-hint contract of the function.  The `apply_overrides` type hinting indicates that it returns an ImplicitDictType (specifically, the same type as the provided `base_object`), but when `parse_result` is false, it does not do this -- instead, it returns a plain dict.  This is a problem when [`op_intent_from_flightrecord` should be returning an `f3548_v21.OperationalIntent`](https://github.com/interuss/monitoring/blob/39dbd67a2d539985e892b35449405ffb94e322fa/monitoring/mock_uss/f3548v21/flight_planning.py#L606) and instead returns a dict.

**Additional context**
See attached report for an example of this problem:

[sequence.zip](https://github.com/user-attachments/files/16901010/sequence.zip)

**Comment by Shastick** [comment]
@BenjaminPelletier, regarding point 2. above: I'm assuming that passing `parse_result=True` in [`op_intent_from_flightrecord`](https://github.com/interuss/monitoring/blob/bd8d6e68108726e9020011a146cfdd1f9ff78780/monitoring/mock_uss/f3548v21/flight_planning.py#L363) is not going to be a sufficient fix: If I do set the flag to true, the flight planning request fails (at least on `f3548_self_contained`) – This makes sense if we're trying to build incorrect objects, just mentiong in case we would actually expect the parsing to succeed.

I'll look into a way of obtaining a proper `f3548_v21.OperationalIntent` object that does not involve parsing the object.

**Comment by BenjaminPelletier** [comment]
Yep, it's a larger conceptual issue -- can't parse an intentionally-invalid object.

**Comment by Shastick** [comment]
#775 proposes to directly mutate the `base_object`. This seems to work. 

If mutation is not desirable I assume we could use [copy.deepcopy()](https://docs.python.org/3/library/copy.html#copy.deepcopy), although I have not tested this yet.

**Comment by Shastick** [comment]
@BenjaminPelletier this _should_ be solved as the problems identifies by this issue have been addressed by #775 and #774, but could you by any change confirm this on the environment where the problem was originally discovered? I'll leave the issue open until then.

**Comment by BenjaminPelletier** [comment]
I haven't been able to positively verify in an environment like the original one, but I believe we can assume this has been fixed until we see otherwise (at which point we can reopen this Issue).
